routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\BookBorrowingCartController;
use App\Http\Controllers\BookBorrowingRequestController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('index');

Route::get('book', [BookController::class, 'index'])->name('book.index');
Route::get('book/{book}', [BookController::class, 'show'])->name('book.show');

Route::middleware('guest')->group(function () {
    Route::get('login', [LoginController::class, 'create'])->name('login.index');
    Route::post('login', [LoginController::class, 'store'])->name('login.authenticate');
    Route::get('register', [RegisterController::class, 'create'])->name('register.index');
    Route::post('register', [RegisterController::class, 'store'])->name('register.store');
});

Route::middleware('auth')->group(function () {
    Route::post('logout', [LoginController::class, 'destroy'])->name('logout');
    Route::middleware('admin')->prefix('admin')->name('admin.')->group(function() {
        Route::get('', [AdminController::class, 'dashboard'])->name('dashboard');
        Route::prefix('member')->name('member.')->group(function() {
            Route::get('', [AdminController::class, 'dataMember'])->name('index');
            Route::get('pending', [AdminController::class, 'pendingMember'])->name('pending');
            Route::put('verify/{id}', [AdminController::class, 'verifyMember'])->name('verify');
            Route::put('reject/{id}', [AdminController::class, 'rejectMember'])->name('reject');
            Route::get('{member}/edit', [AdminController::class, 'editMember'])->name('edit');
            Route::put('{member}', [AdminController::class, 'updateMember'])->name('update');
            Route::delete('{member}', [AdminController::class, 'deleteMember'])->name('delete');
        });
        Route::prefix('book')->name('book.')->group(function() {
            Route::get('create', [BookController::class, 'create'])->name('create');
            Route::post('', [BookController::class, 'store'])->name('store');
            Route::get('{book}/edit', [BookController::class, 'edit'])->name('edit');
            Route::post('{book}/restore', [BookController::class, 'restore'])->name('restore');
            Route::put('{book}', [BookController::class, 'update'])->name('update');
            Route::delete('{book}', [BookController::class, 'destroy'])->name('destroy');
        });
        Route::prefix('bookborrowing')->name('bookborrowing.')->group(function() {
            Route::get('request', [AdminController::class, 'bookBorrowingRequest'])->name('request');
            Route::get('histories', [AdminController::class, 'bookBorrowingHistories'])->name('histories');
            Route::get('pickup', [AdminController::class, 'bookBorrowingPickup'])->name('pickup');
            Route::get('drop', [AdminController::class, 'bookBorrowingDrop'])->name('drop');
            Route::post('', [AdminController::class, 'bookBorrowingProcess'])->name('process');
            Route::post('{book}/active', [AdminController::class, 'bookBorrowingActive'])->name('activated');
            Route::post('{book}/cancel', [AdminController::class, 'bookBorrowingCancel'])->name('cancel');
            Route::post('{book}/return', [AdminController::class, 'bookBorrowingReturn'])->name('return');
        });
    });
    Route::prefix('member')->name('member.')->group(function() {
        Route::get('', [ProfileController::class, 'index'])->name('index');
        Route::get('edit', [ProfileController::class, 'edit'])->name('edit');
        Route::get('create', [ProfileController::class, 'create'])->name('create');
        Route::post('', [ProfileController::class, 'store'])->name('store');
        Route::put('', [ProfileController::class, 'update'])->name('update');
        Route::get('cart', [BookBorrowingCartController::class, 'index'])->name('cart');
        Route::get('borrowingstatus', [BookBorrowingRequestController::class, 'status'])->name('borrowingstatus');
        Route::get('borrowinghistories', [BookBorrowingRequestController::class, 'histories'])->name('borrowinghistories');
    });
    Route::prefix('cart')->name('cart.')->group(function() {
        Route::post('', [BookBorrowingCartController::class, 'store'])->name('store');
        Route::post('add', [BookBorrowingCartController::class, 'add'])->name('add');
        Route::post('subtract', [BookBorrowingCartController::class, 'subtract'])->name('subtract');
        Route::post('request', [BookBorrowingRequestController::class, 'store'])->name('request');
    });
});

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    use HasFactory;
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Models\Book;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use RealRashid\SweetAlert\Facades\Alert;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = DB::table('books')
                ->where('deleted_at', null)
                ->where('title', 'like', '%'.((request()->search != null) ? request()->search : '').'%')
                ->where('borrowable','like', ((request()->borrowable != null) ? request()->borrowable : '%'))
                ->orderBy('created_at', 'desc')->paginate(((request()->entry == 6 || request()->entry == 12 || request()->entry == 24 || request()->entry == 48) ? request()->entry : 6))->withQueryString();
        return view('book.index', ['books' => $books]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.book.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'title' => 'required|string',
            'author' => 'required|string',
            'publisher' => 'required|string',
            'published_in_city' => 'required|string',
            'published_in_year' => 'required|integer',
            'location' => 'required|string',
            'cover_image' => 'nullable|image|file',
            'amount_total' => 'required|integer|min:0',
            'borrowable' => 'required|integer|min:0|max:1',
            'format' => 'nullable|string',
            'pagination' => 'nullable|string',
            'number_of_pages' => 'nullable|integer',
            'dimensions' => 'nullable|string',
            'language' => 'nullable|string',
            'synopsis' => 'nullable|string',
            'work_description' => 'nullable|string',
        ]);

        if($request->file('cover_image')) {
            $validatedData['cover_image'] = $request->file('cover_image')->store('cover-images');
        }
        // dd($validatedData['cover_image']);
        
        $id = DB::table('books')->insertGetId([
            'title' => $validatedData['title'],
            'author' => $validatedData['author'],
            'publisher' => $validatedData['publisher'],
            'published_in_city' => $validatedData['published_in_city'],
            'published_in_year' => $validatedData['published_in_year'],
            'location' => $validatedData['location'],
            'cover_image' => ($request->file('cover_image')) ? $validatedData['cover_image'] : null ,
            'amount_available' => $validatedData['amount_total'],
            'amount_total' => $validatedData['amount_total'],
            'borrowable' => $validatedData['borrowable'],
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        DB::table('details_of_books')->insert([
            'book_id' => $id,
            'format' => ($request->format) ? $validatedData['format'] : null,
            'pagination' => ($request->pagination) ? $validatedData['pagination'] : null,
            'number_of_pages' => ($request->number_of_pages) ? $validatedData['number_of_pages'] : null,
            'dimensions' => ($request->dimensions) ? $validatedData['dimensions'] : null,
            'language' => ($request->language) ? $validatedData['language'] : null,
            'synopsis' => ($request->synopsis) ? $validatedData['synopsis'] : null,
            'work_description' => ($request->work_description) ? $validatedData['work_description'] : null,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        Alert::success('Berhasil', 'Buku baru berhasil ditambahkan');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    // public function show(Book $book)
    public function show($id)
    {
        $book = DB::table('books')->where('id', $id)->first();
        if(Auth::user() != null) {
            if($book == null || $book->deleted_at != null && auth()->user()->is_admin === 0) {
                abort(404);
            }
        } else {
            if($book == null || $book->deleted_at != null) {
                abort(404);
            }
        }
        
        $bookDetail = DB::table('details_of_books')->where('book_id', $id)->first();
        $bookRequests = DB::table('book_borrowing_requests')->where('book_id', $id)->wherein('status', ['approved', 'active'])->get();
        return view('book.show', ['book' => $book, 'bookDetail' => $bookDetail, 'bookRequests' => $bookRequests]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $book = DB::table('books')->where('id', $id)->first();
        $bookDetail = DB::table('details_of_books')->where('book_id', $id)->first();

        return view('admin.book.edit', ['book' => $book, 'bookDetail' => $bookDetail]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'title' => 'required|string',
            'author' => 'required|string',
            'publisher' => 'required|string',
            'published_in_city' => 'required|string',
            'published_in_year' => 'required|integer',
            'location' => 'required|string',
            'cover_image' => 'nullable|image|file',
            'amount_total' => 'required|integer|min:0',
            'borrowable' => 'required|integer|min:0|max:1',
            'format' => 'nullable|string',
            'pagination' => 'nullable|string',
            'number_of_pages' => 'nullable|integer',
            'dimensions' => 'nullable|string',
            'language' => 'nullable|string',
            'synopsis' => 'nullable|string',
            'work_description' => 'nullable|string',
        ]);

        $book = DB::table('books')->where('id', $id)->first();

        if(($book->amount_available + ($validatedData['amount_total'] - $book->amount_total)) < 0) {
            Alert::error('Gagal', 'Jumlah buku tersedia harus lebih dari jumlah buku yang sedang dipinjam');
            return redirect()->back()->withErrors(['amount_total'=>'Jumlah buku tersedia harus lebih dari jumlah buku yang sedang dipinjam']);
        }
        $validatedData['amount_available'] = $book->amount_available + ($validatedData['amount_total'] - $book->amount_total);

        if($request->file('cover_image')) {
            Storage::delete($book->cover_image);
            $validatedData['cover_image'] = $request->file('cover_image')->store('cover-images');
        } else {
            $validatedData['cover_image'] = $book->cover_image;
        }

        DB::table('books')->where('id', $id)->update([
            'title' => $validatedData['title'],
            'author' => $validatedData['author'],
            'publisher' => $validatedData['publisher'],
            'published_in_city' => $validatedData['published_in_city'],
            'published_in_year' => $validatedData['published_in_year'],
            'location' => $validatedData['location'],
            'cover_image' => $validatedData['cover_image'],
            'amount_available' => $validatedData['amount_available'],
            'amount_total' => $validatedData['amount_total'],
            'borrowable' => $validatedData['borrowable'],
            'updated_at' => Carbon::now(),
        ]);

        DB::table('details_of_books')->where('book_id', $id)->update([
            'book_id' => $id,
            'format' => ($request->format) ? $validatedData['format'] : null,
            'pagination' => ($request->pagination) ? $validatedData['pagination'] : null,
            'number_of_pages' => ($request->number_of_pages) ? $validatedData['number_of_pages'] : null,
            'dimensions' => ($request->dimensions) ? $validatedData['dimensions'] : null,
            'language' => ($request->language) ? $validatedData['language'] : null,
            'synopsis' => ($request->synopsis) ? $validatedData['synopsis'] : null,
            'work_description' => ($request->work_description) ? $validatedData['work_description'] : null,
            'updated_at' => Carbon::now(),
        ]);

        Alert::success('Berhasil', 'Buku berhasil diperbarui');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $book = DB::table('books')->where('id', $id)->first();

        if($book->cover_image != null) {
            Storage::delete($book->cover_image);
        }

        DB::table('books')->where('id', $id)->update([
            'cover_image' => null,
            'deleted_at' => Carbon::now()
        ]);

        DB::table('details_of_books')->where('book_id', $id)->update([
            'deleted_at' => Carbon::now()
        ]);
        
        Alert::success('Berhasil', 'Buku berhasil disembunyikan');
        return redirect()->back();
    }

    public function restore($id) {
        DB::table('books')->where('id', $id)->update([
            'deleted_at' => null

resources/views/admin/book/create.blade.php
@extends('layouts.admin')

@section('pageTitle')
    Tambah Buku Baru | Sistem Informasi Perpustakaan
@endsection

@section('bodySection')
    <div class="">
        <div class="fs-5 fw-bold text-bg-success rounded-3 px-3 py-2 bg-gradient">Tambah Buku Baru</div>
        <hr>
        <form action="{{ route('admin.book.store') }}" method="post" enctype="multipart/form-data">
            @csrf
            <div class="mb-3">
                <label for="title" class="form-label">Judul Buku <span class="text-danger fw-bold">*</span></label>
                <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" id="title"
                    value="{{ old('title') }}" placeholder="Judul Buku" required>
            </div>
            <div class="mb-3">
                <label for="author" class="form-label">Penulis Buku <span class="text-danger fw-bold">*</span></label>
                <input type="text" class="form-control @error('author') is-invalid @enderror" name="author" id="author"
                    aria-describedby="authorHelp" value="{{ old('author') }}" placeholder="Penulis Buku" required>
                <small id="authorHelp" class="form-text text-muted">Jika terdapat lebih dari satu penulis, pisahkan dengan
                    <span class="fw-bold">;</span></small>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-3">
                        <label for="publisher" class="form-label">Penerbit <span
                                class="text-danger fw-bold">*</span></label>
                        <input type="text" class="form-control @error('publisher') is-invalid @enderror" name="publisher"
                            id="publisher" value="{{ old('publisher') }}" placeholder="Penerbit" required>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <label for="published_in_city" class="form-label">Kota Terbit <span
                                class="text-danger fw-bold">*</span></label>
                        <input type="text" class="form-control @error('published_in_city') is-invalid @enderror"
                            name="published_in_city" id="published_in_city" value="{{ old('published_in_city') }}"
                            placeholder="Kota Terbit" required>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <label for="published_in_year" class="form-label">Tahun Terbit <span
                                class="text-danger fw-bold">*</span></label>
                        <input type="number" class="form-control @error('published_in_year') is-invalid @enderror"
                            name="published_in_year" id="published_in_year" value="{{ old('published_in_year') }}"
                            placeholder="Tahun Terbit" required>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <label for="location" class="form-label">Lokasi Buku <span
                                class="text-danger fw-bold">*</span></label>
                        <input type="text" class="form-control @error('location') is-invalid @enderror" name="location"
                            id="location" value="{{ old('location') }}" placeholder="Lokasi Buku" required>
                    </div>
                </div>
            </div>
            <div class="mb-3">
                <label for="cover_image" class="form-label">Gambar Cover</label>
                <input type="file" class="form-control @error('cover_image') is-invalid @enderror" name="cover_image"
                    id="cover_image" aria-describedby="coverImageHelp" placeholder="Gambar Cover">
                <small id="coverImageHelp" class="form-text text-muted">Pastikan gambar dapat terlihat dengan jelas</small>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-3">
                        <label for="amount_total" class="form-label">Stok Buku <span
                                class="text-danger fw-bold">*</span></label>
                        <input type="number" class="form-control @error('amount_total') is-invalid @enderror"
                            name="amount_total" id="amount_total" value="{{ old('amount_total') }}"
                            placeholder="Stok Buku" required>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <label for="borrowable" class="form-label">Apa Buku Dapat Dipinjam? <span
                                class="text-danger fw-bold">*</span></label>
                        <select class="form-control @error('borrowable') is-invalid @enderror" name="borrowable"
                            id="borrowable" required>
                            <option value="1" {{ old('borrowable') === 1 ? 'selected' : null }}>Ya, Buku Dapat Dipinjam
                            </option>
                            <option value="0" {{ old('borrowable') === 0 ? 'selected' : null }}>Tidak, Hanya Baca</option>
                        </select>
                    </div>
                </div>
            </div>


            <div class="accordion mb-3" id="informasiTambahan">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="detailBukuTambahan">
                        <button class="accordion-button text-bg-success bg-gradient" type="button" data-bs-toggle="collapse"
                            data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            Detail Buku Tambahan
                        </button>
                    </h2>
                    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="detailBukuTambahan"
                        data-bs-parent="#informasiTambahan">
                        <div class="accordion-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <label for="format" class="form-label">Format Buku</label>
                                        <input type="text" class="form-control @error('format') is-invalid @enderror"
                                            name="format" id="format" value="{{ old('format') }}"
                                            placeholder="Format Buku">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <label for="pagination" class="form-label">Pemberian nomor pada halaman
                                            buku</label>
                                        <input type="text" class="form-control @error('pagination') is-invalid @enderror"
                                            name="pagination" id="pagination" value="{{ old('pagination') }}"
                                            placeholder="Contoh : x, 1000 hlm.">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <label for="number_of_pages" class="form-label">Jumlah Halaman</label>
                                        <input type="number"
                                            class="form-control @error('number_of_pages') is-invalid @enderror"
                                            name="number_of_pages" id="number_of_pages"
                                            value="{{ old('number_of_pages') }}" placeholder="Contoh : 1000">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <label for="dimensions" class="form-label">Dimensi Buku</label>
                                        <input type="text" class="form-control @error('dimensions') is-invalid @enderror"
                                            name="dimensions" id="dimensions" value="{{ old('dimensions') }}"
                                            placeholder="Contoh : 17.5 x 25 cm">
                                    </div>
                                </div>
                            </div>
                            <div class="mb-3">
                                <label for="language" class="form-label">Bahasa</label>
                                <input type="text" class="form-control @error('language') is-invalid @enderror"
                                    name="language" id="language" value="{{ old('language') }}"
                                    placeholder="Contoh : Bahasa Indonesia">
                            </div>
                            <div class="mb-3">
                                <label for="synopsis" class="form-label">Sinopsis Buku</label>
                                <textarea class="form-control @error('synopsis') is-invalid @enderror" name="synopsis" id="synopsis" rows="3">{{ old('synopsis') }}</textarea>
                                <small class="text-muted">Ceritakan dengan singkat tentang isi buku</small>
                            </div>
                            <div class="mb-3">
                                <label for="work_description" class="form-label">Deskripsi Karya</label>
                                <textarea class="form-control @error('work_description') is-invalid @enderror" name="work_description"
                                    id="work_description" rows="3">{{ old('work_description') }}</textarea>
                                <small class="text-muted">Ceritakan dengan singkat tentang karya ini</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-success bg-gradient w-100">Tambah Buku</button>
        </form>
    </div>
@endsection