routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\BookBorrowingCartController;
use App\Http\Controllers\BookBorrowingRequestController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('index');

Route::get('book', [BookController::class, 'index'])->name('book.index');
Route::get('book/{book}', [BookController::class, 'show'])->name('book.show');

Route::middleware('guest')->group(function () {
    Route::get('login', [LoginController::class, 'create'])->name('login.index');
    Route::post('login', [LoginController::class, 'store'])->name('login.authenticate');
    Route::get('register', [RegisterController::class, 'create'])->name('register.index');
    Route::post('register', [RegisterController::class, 'store'])->name('register.store');
});

Route::middleware('auth')->group(function () {
    Route::post('logout', [LoginController::class, 'destroy'])->name('logout');
    Route::middleware('admin')->prefix('admin')->name('admin.')->group(function() {
        Route::get('', [AdminController::class, 'dashboard'])->name('dashboard');
        Route::prefix('member')->name('member.')->group(function() {
            Route::get('', [AdminController::class, 'dataMember'])->name('index');
            Route::get('pending', [AdminController::class, 'pendingMember'])->name('pending');
            Route::put('verify/{id}', [AdminController::class, 'verifyMember'])->name('verify');
            Route::put('reject/{id}', [AdminController::class, 'rejectMember'])->name('reject');
            Route::get('{member}/edit', [AdminController::class, 'editMember'])->name('edit');
            Route::put('{member}', [AdminController::class, 'updateMember'])->name('update');
            Route::delete('{member}', [AdminController::class, 'deleteMember'])->name('delete');
        });
        Route::prefix('book')->name('book.')->group(function() {
            Route::get('create', [BookController::class, 'create'])->name('create');
            Route::post('', [BookController::class, 'store'])->name('store');
            Route::get('{book}/edit', [BookController::class, 'edit'])->name('edit');
            Route::post('{book}/restore', [BookController::class, 'restore'])->name('restore');
            Route::put('{book}', [BookController::class, 'update'])->name('update');
            Route::delete('{book}', [BookController::class, 'destroy'])->name('destroy');
        });
        Route::prefix('bookborrowing')->name('bookborrowing.')->group(function() {
            Route::get('request', [AdminController::class, 'bookBorrowingRequest'])->name('request');
            Route::get('histories', [AdminController::class, 'bookBorrowingHistories'])->name('histories');
            Route::get('pickup', [AdminController::class, 'bookBorrowingPickup'])->name('pickup');
            Route::get('drop', [AdminController::class, 'bookBorrowingDrop'])->name('drop');
            Route::post('', [AdminController::class, 'bookBorrowingProcess'])->name('process');
            Route::post('{book}/active', [AdminController::class, 'bookBorrowingActive'])->name('activated');
            Route::post('{book}/cancel', [AdminController::class, 'bookBorrowingCancel'])->name('cancel');
            Route::post('{book}/return', [AdminController::class, 'bookBorrowingReturn'])->name('return');
        });
    });
    Route::prefix('member')->name('member.')->group(function() {
        Route::get('', [ProfileController::class, 'index'])->name('index');
        Route::get('edit', [ProfileController::class, 'edit'])->name('edit');
        Route::get('create', [ProfileController::class, 'create'])->name('create');
        Route::post('', [ProfileController::class, 'store'])->name('store');
        Route::put('', [ProfileController::class, 'update'])->name('update');
        Route::get('cart', [BookBorrowingCartController::class, 'index'])->name('cart');
        Route::get('borrowingstatus', [BookBorrowingRequestController::class, 'status'])->name('borrowingstatus');
        Route::get('borrowinghistories', [BookBorrowingRequestController::class, 'histories'])->name('borrowinghistories');
    });
    Route::prefix('cart')->name('cart.')->group(function() {
        Route::post('', [BookBorrowingCartController::class, 'store'])->name('store');
        Route::post('add', [BookBorrowingCartController::class, 'add'])->name('add');
        Route::post('subtract', [BookBorrowingCartController::class, 'subtract'])->name('subtract');
        Route::post('request', [BookBorrowingRequestController::class, 'store'])->name('request');
    });
});

resources/views/admin/bookborrowing/drop.blade.php
@extends('layouts.admin')

@section('pageTitle')
    Pengembalian Buku | Sistem Informasi Perpustakaan
@endsection

@section('bodySection')
    <div class="">
        <div class="fs-5 fw-bold text-bg-success rounded-3 px-3 py-2 bg-gradient">Pengembalian Buku</div>
        <hr>

        <form action="{{ route('admin.bookborrowing.drop') }}" method="get">
            <div class="input-group mb-3">
                <input type="number" name="user_id" class="form-control" placeholder="Masukkan User ID">
                <button class="btn btn-outline-success" type="submit"><i class="fas fa-search"></i></button>
            </div>
        </form>

        @if ($bookBorrowingRequests->count() != 0)
            <div class="text-muted">Menampilkan
                {{ $bookBorrowingRequests->perPage() > $bookBorrowingRequests->total() ? $bookBorrowingRequests->total() : $bookBorrowingRequests->perPage() }}
                dari
                {{ $bookBorrowingRequests->total() }} permintaan</div>
            @foreach ($bookBorrowingRequests as $bookBorrowingRequest)
                <div class="card mb-3" id="request{{ $bookBorrowingRequest->id }}">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-3 col-md-2 col-xl-1">
                                @if ($bookBorrowingRequest->book->cover_image != null)
                                    <img src="{{ asset('storage/' . $bookBorrowingRequest->book->cover_image) }}"
                                        class="img-fluid" style="max-height: 100px" alt="">
                                @else
                                    <img src="{{ asset('img/image-not-found.png') }}" class="img-fluid"
                                        style="max-height: 100px" alt="">
                                @endif
                            </div>
                            <div class="col-9 col-md-6 col-xl-8">
                                <div class="fw-semibold">{{ $bookBorrowingRequest->book->title }}</div>
                                <div class="d-none d-md-block">
                                    <div class="text-muted">By {{ $bookBorrowingRequest->book->author }},
                                        Publisher :
                                        {{ $bookBorrowingRequest->book->publisher }}</div>
                                </div>
                                <div class="">Peminjaman a.n. {{ $bookBorrowingRequest->user->name }}
                                    id({{ $bookBorrowingRequest->user_id }})</div>
                                <div class="">Batas akhir pengembalian
                                    {{ \Carbon\Carbon::parse($bookBorrowingRequest->updated_at)->addDays(7)->format('d M Y') }}
                                </div>
                            </div>
                            <div class="col-12 col-md-4 col-xl-3 d-flex align-items-center">
                                <div class="w-100">
                                    <hr class="d-md-none">
                                    <button type="button" class="btn btn-sm btn-success bg-gradient w-100 mb-3"
                                        onclick="bookReturned({{ $bookBorrowingRequest->id }})">Buku
                                        sudah dikembalikan</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
            {{ $bookBorrowingRequests->links() }}
        @else
            <div class="fw-semibold">Tidak ada data buku yang akan diambil pada saat ini</div>
        @endif
    </div>
@endsection

@push('script')
    <script>
        function bookReturned(id) {
            console.log(id);
            let url = "{{ url('/') }}/admin/bookborrowing/" + id + "/return";
            let xhr = new XMLHttpRequest();

            xhr.open("POST", url, true);
            xhr.setRequestHeader("X-CSRF-TOKEN", "{{ csrf_token() }}");
            xhr.setRequestHeader("content-type", "application/json");
            xhr.onload = function() {
                var response = JSON.parse(xhr.response);
                if (xhr.readyState == 4 && xhr.status == "200") {
                    if (response['status'] == 200) {
                        let card = document.getElementById('request' + id);
                        card.parentNode.removeChild(card);
                        Toast.fire(
                            'Berhasil',
                            'Pengembalian buku berhasil direkap',
                            'success'
                        )
                    } else {
                        Toast.fire(
                            'Gagal',
                            'Pengembalian buku gagal direkap',
                            'error'
                        )
                    }
                } else {
                    Toast.fire(
                        'Gagal',
                        'Pengembalian buku gagal direkap',
                        'error'
                    )
                }
            }
            xhr.send();
        }
    </script>
@endpush

resources/views/admin/bookborrowing/histories.blade.php
@extends('layouts.admin')

@section('pageTitle')
    Ajuan Peminjaman | Sistem Informasi Perpustakaan
@endsection

@section('bodySection')
    <div class="">
        <div class="fs-5 fw-bold text-bg-success rounded-3 px-3 py-2 bg-gradient">Pengambilan Buku</div>
        <hr>
        @if ($bookBorrowingHistories->count() != 0)
            @foreach ($bookBorrowingHistories as $bookHistory)
                <div class="row mb-3">
                    <div class="col-3 col-md-2 col-xl-1">
                        @if ($bookHistory->book->cover_image != null)
                            <img src="{{ asset('storage/' . $bookHistory->book->cover_image) }}" class="img-fluid"
                                style="max-height: 100px" alt="">
                        @else
                            <img src="{{ asset('img/image-not-found.png') }}" class="img-fluid" style="max-height: 100px"
                                alt="">
                        @endif
                    </div>
                    <div class="col-9 col-md-10 col-xl-11">
                        <div class="fw-semibold">{{ $bookHistory->book->title }}</div>
                        <div class="d-none d-md-block">
                            <div class="text-muted">By {{ $bookHistory->book->author }}, Publisher :
                                {{ $bookHistory->book->publisher }}</div>
                        </div>
                        <div class="">Status : <b>{{ Str::upper($bookHistory->status) }}</b></div>
                        <div class="text-muted">
                            @if ($bookHistory->status == 'pending')
                                Diajukan tanggal
                            @elseif ($bookHistory->status == 'approved')
                                Disetujui tanggal
                            @elseif ($bookHistory->status == 'disapproved')
                                Ditolak tanggal
                            @elseif ($bookHistory->status == 'active')
                                Dipinjam sejak tanggal
                            @elseif ($bookHistory->status == 'returned')
                                Dikembalikan tanggal
                            @endif
                            {{ \Carbon\Carbon::parse(auth()->user()->updated_at)->format('d M Y') }}
                        </div>
                    </div>
                </div>
                <hr>
            @endforeach
            {{ $bookBorrowingHistories->links() }}
        @else
            <div class=" fw-semibold text-center">Tidak ada permintaan buku yang sedang diproses, diterima, ataupun buku
                yang sedang dipinjam</div>
        @endif
    </div>
@endsection

resources/views/admin/bookborrowing/pickup.blade.php
@extends('layouts.admin')

@section('pageTitle')
    Ajuan Peminjaman | Sistem Informasi Perpustakaan
@endsection

@section('bodySection')
    <div class="">
        <div class="fs-5 fw-bold text-bg-success rounded-3 px-3 py-2 bg-gradient">Pengambilan Buku</div>
        <hr>

        <form action="{{ route('admin.bookborrowing.pickup') }}" method="get">
            <div class="input-group mb-3">
                <input type="number" name="user_id" class="form-control" placeholder="Masukkan User ID">
                <button class="btn btn-outline-success" type="submit"><i class="fas fa-search"></i></button>
            </div>
        </form>

        @if ($bookBorrowingRequests->count() != 0)
            <div class="text-muted">Menampilkan
                {{ $bookBorrowingRequests->perPage() > $bookBorrowingRequests->total() ? $bookBorrowingRequests->total() : $bookBorrowingRequests->perPage() }}
                dari
                {{ $bookBorrowingRequests->total() }} permintaan</div>
            @foreach ($bookBorrowingRequests as $bookBorrowingRequest)
                <div class="card mb-3" id="request{{ $bookBorrowingRequest->id }}">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-3 col-md-2 col-xl-1">
                                @if ($bookBorrowingRequest->book->cover_image != null)
                                    <img src="{{ asset('storage/' . $bookBorrowingRequest->book->cover_image) }}"
                                        class="img-fluid" style="max-height: 100px" alt="">
                                @else
                                    <img src="{{ asset('img/image-not-found.png') }}" class="img-fluid"
                                        style="max-height: 100px" alt="">
                                @endif
                            </div>
                            <div class="col-9 col-md-6 col-xl-8">
                                <div class="fw-semibold">{{ $bookBorrowingRequest->book->title }}</div>
                                <div class="d-none d-md-block">
                                    <div class="text-muted">By {{ $bookBorrowingRequest->book->author }},
                                        Publisher :
                                        {{ $bookBorrowingRequest->book->publisher }}</div>
                                </div>
                                <div class="">Permintaan dari {{ $bookBorrowingRequest->user->name }}
                                    id({{ $bookBorrowingRequest->user_id }})</div>
                                <div class="">Batas akhir pengambilan
                                    {{ \Carbon\Carbon::parse($bookBorrowingRequest->updated_at)->addDays(3)->format('d M Y') }}
                                </div>
                            </div>
                            <div class="col-12 col-md-4 col-xl-3">
                                <hr class="d-md-none">
                                <button type="button" class="btn btn-sm btn-success bg-gradient w-100 mb-3"
                                    onclick="bookActivated({{ $bookBorrowingRequest->id }})">Buku
                                    sudah diambil</button>
                                <button type="button" class="btn btn-sm btn-outline-danger bg-gradient w-100"
                                    onclick="bookCancelled({{ $bookBorrowingRequest->id }})">Buku
                                    batal diambil</button>

                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
            {{ $bookBorrowingRequests->links() }}
        @else
            <div class="fw-semibold">Tidak ada data buku yang akan diambil pada saat ini</div>
        @endif
    </div>
@endsection

@push('script')
    <script>
        function bookActivated(id) {
            console.log(id);
            let url = "{{ url('/') }}/admin/bookborrowing/" + id + "/active";
            let xhr = new XMLHttpRequest();

            xhr.open("POST", url, true);
            xhr.setRequestHeader("X-CSRF-TOKEN", "{{ csrf_token() }}");
            xhr.setRequestHeader("content-type", "application/json");
            xhr.onload = function() {
                var response = JSON.parse(xhr.response);
                if (xhr.readyState == 4 && xhr.status == "200") {
                    if (response['status'] == 200) {
                        let card = document.getElementById('request' + id);
                        card.parentNode.removeChild(card);
                        Toast.fire(
                            'Berhasil',
                            'Pengambilan buku berhasil direkap',
                            'success'
                        )
                    } else {
                        Toast.fire(
                            'Gagal',
                            'Pengambilan buku gagal direkap',
                            'error'
                        )
                    }
                } else {
                    Toast.fire(
                        'Gagal',
                        'Pengambilan buku gagal direkap',
                        'error'
                    )
                }
            }
            xhr.send();
        }

        function bookCancelled(id) {
            console.log(id);
            let url = "{{ url('/') }}/admin/bookborrowing/" + id + "/cancel";
            let xhr = new XMLHttpRequest();

            xhr.open("POST", url, true);
            xhr.setRequestHeader("X-CSRF-TOKEN", "{{ csrf_token() }}");
            xhr.setRequestHeader("content-type", "application/json");
            xhr.onload = function() {
                var response = JSON.parse(xhr.response);
                if (xhr.readyState == 4 && xhr.status == "200") {
                    if (response['status'] == 200) {
                        let card = document.getElementById('request' + id);
                        card.parentNode.removeChild(card);
                        Toast.fire(
                            'Berhasil',
                            'Pembatalan pengambilan buku berhasil direkap',
                            'success'
                        )
                    } else {
                        Toast.fire(
                            'Gagal',
                            'Pembatalan pengambilan buku gagal direkap',
                            'error'
                        )
                    }
                } else {
                    Toast.fire(
                        'Gagal',
                        'Pembatalan pengambilan buku gagal direkap',
                        'error'
                    )
                }
            }
            xhr.send();
        }
    </script>
@endpush

resources/views/admin/bookborrowing/request.blade.php
@extends('layouts.admin')

@section('pageTitle')
    Ajuan Peminjaman | Sistem Informasi Perpustakaan
@endsection

@section('bodySection')
    <div class="">
        <div class="fs-5 fw-bold text-bg-success rounded-3 px-3 py-2 bg-gradient">Ajuan Peminjaman</div>
        <hr>

        @if ($bookBorrowingRequests->count() != 0)
            <div class="text-muted">Menampilkan
                {{ $bookBorrowingRequests->perPage() > $bookBorrowingRequests->total() ? $bookBorrowingRequests->total() : $bookBorrowingRequests->perPage() }}
                dari
                {{ $bookBorrowingRequests->total() }} permintaan</div>
            <form action="{{ route('admin.bookborrowing.process') }}" method="post">
                @csrf
                @foreach ($bookBorrowingRequests as $bookBorrowingRequest)
                    <div class="card mb-3">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-3 col-md-2 col-xl-1">
                                    @if ($bookBorrowingRequest->book->cover_image != null)
                                        <img src="{{ asset('storage/' . $bookBorrowingRequest->book->cover_image) }}"
                                            class="img-fluid" style="max-height: 100px" alt="">
                                    @else
                                        <img src="{{ asset('img/image-not-found.png') }}" class="img-fluid"
                                            style="max-height: 100px" alt="">
                                    @endif
                                </div>
                                <div class="col-9 col-md-6 col-xl-8">
                                    <div class="fw-semibold">{{ $bookBorrowingRequest->book->title }}</div>
                                    <div class="d-none d-md-block">
                                        <div class="text-muted">By {{ $bookBorrowingRequest->book->author }},
                                            Publisher :
                                            {{ $bookBorrowingRequest->book->publisher }}</div>
                                    </div>
                                    <div class="">Permintaan dari {{ $bookBorrowingRequest->user->name }}
                                        id({{ $bookBorrowingRequest->user_id }})</div>
                                </div>
                                <div class="col-12 col-md-4 col-xl-3">
                                    <hr class="d-md-none">
                                    <div class="">
                                        Terima Permintaan?
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" type="radio"
                                            name="requestId[{{ $bookBorrowingRequest->id }}]"
                                            id="approve{{ $bookBorrowingRequest->id }}" value="1">
                                        <label class="form-check-label" for="approve{{ $bookBorrowingRequest->id }}">
                                            Ya, terima permintaan
                                        </label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" type="radio"
                                            name="requestId[{{ $bookBorrowingRequest->id }}]"
                                            id="approve{{ $bookBorrowingRequest->id }}" value="0">
                                        <label class="form-check-label" for="approve{{ $bookBorrowingRequest->id }}">
                                            Tidak, tolak permintaan
                                        </label>
                                    </div>
                                    <div class="">
                                        {{ $bookBorrowingRequest->book->amount_available > 0 ? null : 'Stok Buku habis' }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
                <button type="submit" class="btn btn-success bg-gradient w-100">Update Permintaan</button>
            </form>
            {{ $bookBorrowingRequests->links() }}
        @else
            <div class="fw-semibold">Tidak ada ajuan peminjaman pada saat ini</div>
        @endif
    </div>
@endsection