routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\BookBorrowingCartController;
use App\Http\Controllers\BookBorrowingRequestController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('index');

Route::get('book', [BookController::class, 'index'])->name('book.index');
Route::get('book/{book}', [BookController::class, 'show'])->name('book.show');

Route::middleware('guest')->group(function () {
    Route::get('login', [LoginController::class, 'create'])->name('login.index');
    Route::post('login', [LoginController::class, 'store'])->name('login.authenticate');
    Route::get('register', [RegisterController::class, 'create'])->name('register.index');
    Route::post('register', [RegisterController::class, 'store'])->name('register.store');
});

Route::middleware('auth')->group(function () {
    Route::post('logout', [LoginController::class, 'destroy'])->name('logout');
    Route::middleware('admin')->prefix('admin')->name('admin.')->group(function() {
        Route::get('', [AdminController::class, 'dashboard'])->name('dashboard');
        Route::prefix('member')->name('member.')->group(function() {
            Route::get('', [AdminController::class, 'dataMember'])->name('index');
            Route::get('pending', [AdminController::class, 'pendingMember'])->name('pending');
            Route::put('verify/{id}', [AdminController::class, 'verifyMember'])->name('verify');
            Route::put('reject/{id}', [AdminController::class, 'rejectMember'])->name('reject');
            Route::get('{member}/edit', [AdminController::class, 'editMember'])->name('edit');
            Route::put('{member}', [AdminController::class, 'updateMember'])->name('update');
            Route::delete('{member}', [AdminController::class, 'deleteMember'])->name('delete');
        });
        Route::prefix('book')->name('book.')->group(function() {
            Route::get('create', [BookController::class, 'create'])->name('create');
            Route::post('', [BookController::class, 'store'])->name('store');
            Route::get('{book}/edit', [BookController::class, 'edit'])->name('edit');
            Route::post('{book}/restore', [BookController::class, 'restore'])->name('restore');
            Route::put('{book}', [BookController::class, 'update'])->name('update');
            Route::delete('{book}', [BookController::class, 'destroy'])->name('destroy');
        });
        Route::prefix('bookborrowing')->name('bookborrowing.')->group(function() {
            Route::get('request', [AdminController::class, 'bookBorrowingRequest'])->name('request');
            Route::get('histories', [AdminController::class, 'bookBorrowingHistories'])->name('histories');
            Route::get('pickup', [AdminController::class, 'bookBorrowingPickup'])->name('pickup');
            Route::get('drop', [AdminController::class, 'bookBorrowingDrop'])->name('drop');
            Route::post('', [AdminController::class, 'bookBorrowingProcess'])->name('process');
            Route::post('{book}/active', [AdminController::class, 'bookBorrowingActive'])->name('activated');
            Route::post('{book}/cancel', [AdminController::class, 'bookBorrowingCancel'])->name('cancel');
            Route::post('{book}/return', [AdminController::class, 'bookBorrowingReturn'])->name('return');
        });
    });
    Route::prefix('member')->name('member.')->group(function() {
        Route::get('', [ProfileController::class, 'index'])->name('index');
        Route::get('edit', [ProfileController::class, 'edit'])->name('edit');
        Route::get('create', [ProfileController::class, 'create'])->name('create');
        Route::post('', [ProfileController::class, 'store'])->name('store');
        Route::put('', [ProfileController::class, 'update'])->name('update');
        Route::get('cart', [BookBorrowingCartController::class, 'index'])->name('cart');
        Route::get('borrowingstatus', [BookBorrowingRequestController::class, 'status'])->name('borrowingstatus');
        Route::get('borrowinghistories', [BookBorrowingRequestController::class, 'histories'])->name('borrowinghistories');
    });
    Route::prefix('cart')->name('cart.')->group(function() {
        Route::post('', [BookBorrowingCartController::class, 'store'])->name('store');
        Route::post('add', [BookBorrowingCartController::class, 'add'])->name('add');
        Route::post('subtract', [BookBorrowingCartController::class, 'subtract'])->name('subtract');
        Route::post('request', [BookBorrowingRequestController::class, 'store'])->name('request');
    });
});

resources/views/layouts/components/footer.blade.php
<p class="text-center bg-success bg-gradient py-3 text-light">&copy; 2022 Powered by <a
        href="https://linkedin.com/in/readone" class="text-light fw-semibold">Muhammad
        Ridwan Fauzi</a> </p>

resources/views/layouts/components/navbar.blade.php
<nav class="navbar navbar-expand-md bg-light bg-gradient fixed-top shadow-lg">
    <div class="container">
        <a class="navbar-brand text-success" href="{{ route('index') }}"><i class="fas fa-book fa-fw"></i> UNI
            E-Library</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <hr>
                <li class="nav-item">
                    <a href="{{ route('book.index') }}" class="nav-link">Daftar Buku</a>
                </li>
                <hr>
                @guest
                    <li class="nav-item">
                        <a class="nav-link btn btn-success text-light bg-gradient"
                            href="{{ route('login.index') }}">Login</a>
                    </li>
                @endguest
                @auth
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            {{ auth()->user()->name }}
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            @if (auth()->user()->is_admin)
                                <li><a class="dropdown-item" href="{{ route('admin.dashboard') }}">Dashboard</a></li>
                            @else
                                <li><a class="dropdown-item" href="{{ route('member.index') }}">User Panel</a></li>
                                <li><a class="dropdown-item" href="{{ route('member.cart') }}">Keranjang
                                        Peminjaman</a>
                                </li>
                                <li><a class="dropdown-item" href="{{ route('member.borrowingstatus') }}">Status
                                        Peminjaman</a></li>
                            @endif
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item text-bg-success" href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                                                                                                                                                                                                                                            document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }} <i class="fa fa-sign-out"></i>
                                </a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                    style="display: none;">
                                    @csrf
                                </form>
                            </li>
                        </ul>
                    </li>
                @endauth
            </ul>
        </div>
    </div>
</nav>
<nav class="navbar navbar-expand-md">
    <div class="container">
        <a class="navbar-brand text-success" href="{{ route('index') }}"><i class="fas fa-book fa-fw"></i> UNI
            E-Library</a>
    </div>
</nav>

resources/views/layouts/components/searchbar.blade.php
<div class="bg-success bg-gradient">
    <div class="container">
        <div class="px-4 py-5">
            <form action="{{ route('book.index') }}" method="get" name="search">
                <div class="input-group mb-3 mx-auto" style="max-width: 540px">
                    <input type="text" class="form-control" name="search" value="{{ request()->search }}"
                        placeholder="Cari buku...">
                    <button class="btn btn-outline-light bg-gradient" type="submit"><i
                            class="fas fa-search"></i></button>
            </form>
        </div>
    </div>
</div>
</div>