routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\BookBorrowingCartController;
use App\Http\Controllers\BookBorrowingRequestController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('index');

Route::get('book', [BookController::class, 'index'])->name('book.index');
Route::get('book/{book}', [BookController::class, 'show'])->name('book.show');

Route::middleware('guest')->group(function () {
    Route::get('login', [LoginController::class, 'create'])->name('login.index');
    Route::post('login', [LoginController::class, 'store'])->name('login.authenticate');
    Route::get('register', [RegisterController::class, 'create'])->name('register.index');
    Route::post('register', [RegisterController::class, 'store'])->name('register.store');
});

Route::middleware('auth')->group(function () {
    Route::post('logout', [LoginController::class, 'destroy'])->name('logout');
    Route::middleware('admin')->prefix('admin')->name('admin.')->group(function() {
        Route::get('', [AdminController::class, 'dashboard'])->name('dashboard');
        Route::prefix('member')->name('member.')->group(function() {
            Route::get('', [AdminController::class, 'dataMember'])->name('index');
            Route::get('pending', [AdminController::class, 'pendingMember'])->name('pending');
            Route::put('verify/{id}', [AdminController::class, 'verifyMember'])->name('verify');
            Route::put('reject/{id}', [AdminController::class, 'rejectMember'])->name('reject');
            Route::get('{member}/edit', [AdminController::class, 'editMember'])->name('edit');
            Route::put('{member}', [AdminController::class, 'updateMember'])->name('update');
            Route::delete('{member}', [AdminController::class, 'deleteMember'])->name('delete');
        });
        Route::prefix('book')->name('book.')->group(function() {
            Route::get('create', [BookController::class, 'create'])->name('create');
            Route::post('', [BookController::class, 'store'])->name('store');
            Route::get('{book}/edit', [BookController::class, 'edit'])->name('edit');
            Route::post('{book}/restore', [BookController::class, 'restore'])->name('restore');
            Route::put('{book}', [BookController::class, 'update'])->name('update');
            Route::delete('{book}', [BookController::class, 'destroy'])->name('destroy');
        });
        Route::prefix('bookborrowing')->name('bookborrowing.')->group(function() {
            Route::get('request', [AdminController::class, 'bookBorrowingRequest'])->name('request');
            Route::get('histories', [AdminController::class, 'bookBorrowingHistories'])->name('histories');
            Route::get('pickup', [AdminController::class, 'bookBorrowingPickup'])->name('pickup');
            Route::get('drop', [AdminController::class, 'bookBorrowingDrop'])->name('drop');
            Route::post('', [AdminController::class, 'bookBorrowingProcess'])->name('process');
            Route::post('{book}/active', [AdminController::class, 'bookBorrowingActive'])->name('activated');
            Route::post('{book}/cancel', [AdminController::class, 'bookBorrowingCancel'])->name('cancel');
            Route::post('{book}/return', [AdminController::class, 'bookBorrowingReturn'])->name('return');
        });
    });
    Route::prefix('member')->name('member.')->group(function() {
        Route::get('', [ProfileController::class, 'index'])->name('index');
        Route::get('edit', [ProfileController::class, 'edit'])->name('edit');
        Route::get('create', [ProfileController::class, 'create'])->name('create');
        Route::post('', [ProfileController::class, 'store'])->name('store');
        Route::put('', [ProfileController::class, 'update'])->name('update');
        Route::get('cart', [BookBorrowingCartController::class, 'index'])->name('cart');
        Route::get('borrowingstatus', [BookBorrowingRequestController::class, 'status'])->name('borrowingstatus');
        Route::get('borrowinghistories', [BookBorrowingRequestController::class, 'histories'])->name('borrowinghistories');
    });
    Route::prefix('cart')->name('cart.')->group(function() {
        Route::post('', [BookBorrowingCartController::class, 'store'])->name('store');
        Route::post('add', [BookBorrowingCartController::class, 'add'])->name('add');
        Route::post('subtract', [BookBorrowingCartController::class, 'subtract'])->name('subtract');
        Route::post('request', [BookBorrowingRequestController::class, 'store'])->name('request');
    });
});

resources/views/admin/member/edit.blade.php
@extends('layouts.admin')

@section('pageTitle')
    Data Member | Sistem Informasi Perpustakaan
@endsection

@section('bodySection')
    <div class="">
        <div class="fs-5 fw-bold text-bg-success rounded-3 px-3 py-2 bg-gradient">Data Member</div>
        <hr>
        <div class="fs-5 fw-semibold text-uppercase text-center mb-3">Identitas Member</div>
        <dl class="row">
            <dt class="col-md-4 text-md-end">Nama Lengkap</dt>
            <dd class="col-md-8">{{ $user->name }}</dd>
            <dt class="col-md-4 text-md-end">Alamat E-mail</dt>
            <dd class="col-md-8">{{ $user->email }}</dd>
            <dt class="col-md-4 text-md-end">Nomor Induk Mahasiswa</dt>
            <dd class="col-md-8">{{ $profile->nim }}</dd>
            <dt class="col-md-4 text-md-end">Fakultas</dt>
            <dd class="col-md-8">{{ $profile->faculty_name }}</dd>
            <dt class="col-md-4 text-md-end">Jurusan</dt>
            <dd class="col-md-8">{{ $profile->major_name }}</dd>
            <dt class="col-md-4 text-md-end">Tahun Masuk</dt>
            <dd class="col-md-8">{{ $profile->entrance_year }}</dd>
            <dt class="col-md-4 text-md-end">Nomor Telepon</dt>
            <dd class="col-md-8">{{ $profile->phone_number }}</dd>
            <dt class="col-md-4 text-md-end">Alamat</dt>
            <dd class="col-md-8">{{ $profile->address }}</dd>
            <dt class="col-md-4 text-md-end">Status Member</dt>
            <dd class="col-md-8">{{ $user->is_member ? 'Member' : 'Belum diverifikasi Admin' }}</dd>
            <dt class="col-md-4 text-md-end">Tanggal Bergabung</dt>
            <dd class="col-md-8">{{ \Carbon\Carbon::parse($user->created_at)->format('d M Y H:i:s') }}
            </dd>
            <dt class="col-md-4 text-md-end">Terakhir Diperbarui</dt>
            <dd class="col-md-8">{{ \Carbon\Carbon::parse($user->updated_at)->format('d M Y H:i:s') }}
            </dd>
        </dl>
        <div class="fs-5 fw-semibold text-uppercase text-center mb-3">Ubah Data</div>
        <form action="{{ route('admin.member.update', ['member' => $user->id]) }}" method="post">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-3">
                        <label for="valid_profile" class="form-label">Apa profile-nya valid?</label>
                        <select class="form-control" name="valid_profile" id="valid_profile">
                            <option value="1"
                                {{ (old('valid_profile') ? old('valid_profile') : $user->valid_profile) == 1 ? 'selected' : null }}>
                                Ya, profile valid</option>
                            <option value="0"
                                {{ (old('valid_profile') ? old('valid_profile') : $user->valid_profile) == 0 ? 'selected' : null }}>
                                Tidak, profile tidak valid</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <label for="is_member" class="form-label">Status Member?</label>
                        <select class="form-control" name="is_member" id="is_member">
                            <option value="1"
                                {{ (old('is_member') ? old('is_member') : $user->is_member) == 1 ? 'selected' : null }}>
                                Member</option>
                            <option value="0"
                                {{ (old('is_member') ? old('is_member') : $user->is_member) == 0 ? 'selected' : null }}>
                                Bukan Member</option>
                        </select>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-success bg-gradient w-100">Ubah data member</button>
        </form>
    </div>
@endsection

resources/views/admin/member/index.blade.php
@extends('layouts.admin')

@section('pageTitle')
    Data Member | Sistem Informasi Perpustakaan
@endsection

@section('bodySection')
    <div class="">
        <div class="fs-5 fw-bold text-bg-success rounded-3 px-3 py-2 bg-gradient">Data Member</div>
        <hr>
        @forelse ($users as $user)
            <div class="card mb-3" id="user{{ $user->id }}">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-9">
                            <div class="fw-semibold">{{ $user->name }}</div>
                            <div class="text-muted">Status : {{ $user->is_member ? 'Member' : 'Bukan Member' }}</div>
                            <div class="">Bergabung sejak :
                                {{ \Carbon\Carbon::parse($user->created_at)->format('d M Y') }}</div>
                        </div>
                        <div class="col-md-3">
                            <hr class="d-md-none">
                            <a href="{{ route('admin.member.edit', ['member' => $user->id]) }}"
                                class="btn btn-sm btn-success bg-gradient w-100 mb-2">Edit Member</a>
                            <button type="button" class="btn btn-sm btn-outline-danger bg-gradient w-100"
                                onclick="removeUser({{ $user->id }})">Hapus
                                Member</button>
                        </div>
                    </div>
                </div>
            </div>
        @empty
            <div class="">Belum ada satupun member</div>
        @endforelse
        {{ $users->links() }}
    </div>
@endsection

@push('script')
    <script>
        function removeUser(id) {
            Swal.fire({
                title: 'Anda Yakin?',
                text: "User akan menjadi non-aktif dan tidak dapat login",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#198754',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ya, hapus user!'
            }).then((result) => {
                if (result.isConfirmed) {

                    let userId = id;
                    let url = "/admin/member/";
                    let xhr = new XMLHttpRequest();

                    xhr.open("DELETE", url + userId, true);
                    xhr.setRequestHeader("X-CSRF-TOKEN", "{{ csrf_token() }}");
                    xhr.setRequestHeader("content-type", "application/json");
                    xhr.onload = function() {
                        var response = JSON.parse(xhr.response);
                        if (xhr.readyState == 4 && xhr.status == "200") {
                            if (response['status'] == 200) {
                                let card = document.getElementById('user' + id)
                                card.parentNode.removeChild(card)
                                Toast.fire(
                                    'Berhasil',
                                    'User berhasil dihapus',
                                    'success'
                                )
                            } else {
                                Toast.fire(
                                    'Gagal',
                                    'User gagal dihapus',
                                    'error'
                                )
                            }
                        } else {
                            Toast.fire(
                                'Gagal',
                                'User gagal dihapus',
                                'error'
                            )
                        }
                    }
                    xhr.send();

                }
            })
        }
    </script>
@endpush

resources/views/admin/member/pending.blade.php
@extends('layouts.admin')

@section('pageTitle')
    Pendaftar Baru | Sistem Informasi Perpustakaan
@endsection

@section('bodySection')
    <div class="">
        <div class="fs-5 fw-bold text-bg-success rounded-3 px-3 py-2 bg-gradient">Pendaftar Baru</div>
        <hr>
        @forelse ($pendingUsers as $pendingUser)
            <div class="" id="pendingUser{{ $pendingUser->id }}">
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="row d-flex align-items-center">
                            <div class="col-md-9">
                                <div class="fw-semibold">{{ $pendingUser->name }}</div>
                                <div class="text-muted">No. Telpon : {{ $pendingUser->profile->phone_number }}
                                </div>
                                <div class="">{{ $pendingUser->profile->address }}</div>
                            </div>
                            <div class="col-md-3">
                                <hr class="d-block d-md-none">
                                <button type="button" class="btn btn-success btn-sm bg-gradient w-100 mb-3"
                                    onclick="verifyMember({{ $pendingUser->id }})">Jadikan Member</button>
                                <button type="button" class="btn btn-outline-danger btn-sm bg-gradient w-100"
                                    onclick="rejectMember({{ $pendingUser->id }})">Data Belum Valid</button>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @empty
            <div class="fw-semibold">Belum ada lagi member baru yang daftar</div>
        @endforelse
    </div>
@endsection

@push('script')
    <script>
        function verifyMember(id) {
            console.log(id);
            var url = "/admin/member/verify/";
            var xhr = new XMLHttpRequest();

            xhr.open("PUT", url + id, true);
            xhr.setRequestHeader("X-CSRF-TOKEN", "{{ csrf_token() }}");
            xhr.setRequestHeader("content-type", "application/json");
            xhr.onload = function() {
                var response = JSON.parse(xhr.response);
                if (xhr.readyState == 4 && xhr.status == "200") {
                    if (response['status'] == 200) {
                        var element = document.getElementById('pendingUser' + id + '');
                        element.parentNode.removeChild(element);
                        Toast.fire(
                            'Berhasil',
                            'Member dengan id ' + id + ' berhasil diverifikasi',
                            'success'
                        )
                    } else {
                        Toast.fire(
                            'Gagal',
                            'Member dengan id ' + id + ' gagal diverifikasi',
                            'error'
                        )
                    }
                } else {
                    Toast.fire(
                        'Gagal',
                        'Member dengan id ' + id + ' gagal diverifikasi',
                        'error'
                    )
                }
            }
            xhr.send();
        }

        function rejectMember(id) {
            console.log(id);
            var url = "/admin/member/reject/";
            var xhr = new XMLHttpRequest();

            xhr.open("PUT", url + id, true);
            xhr.setRequestHeader("X-CSRF-TOKEN", "{{ csrf_token() }}");
            xhr.setRequestHeader("content-type", "application/json");
            xhr.onload = function() {
                var response = JSON.parse(xhr.response);
                if (xhr.readyState == 4 && xhr.status == "200") {
                    if (response.status == 200) {
                        var element = document.getElementById('pendingUser' + id + '');
                        element.parentNode.removeChild(element);
                        Toast.fire(
                            'Berhasil',
                            'Pengajuan member dengan id ' + id + ' berhasil ditolak',
                            'success'
                        )
                    } else {
                        Toast.fire(
                            'Gagal',
                            'Pengajuan Member dengan id ' + id + ' gagal ditolak',
                            'error'
                        )
                    }
                } else {
                    Toast.fire(
                        'Gagal',
                        'Member dengan id ' + id + ' gagal diverifikasi',
                        'error'
                    )
                }
            }
            xhr.send();
        }
    </script>
@endpush